import { Injectable } from '@angular/core';
import { BehaviorSubject, Observable } from 'rxjs';

export interface Language {
  code: string;
  name: string;
  flag: string;
}

export interface Translations {
  [key: string]: string;
}

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  private currentLanguage = new BehaviorSubject<string>('en');
  currentLanguage$ = this.currentLanguage.asObservable();

    readonly languages: Language[] = [
        { code: 'en', name: 'English', flag: '🇬🇧' },
        { code: 'es', name: 'Spanish', flag: '🇪🇸' },
        { code: 'fr', name: 'French', flag: '🇫🇷' },
        { code: 'de', name: 'German', flag: '🇩🇪' },
        { code: 'it', name: 'Italian', flag: '🇮🇹' },
        { code: 'pt', name: 'Portuguese', flag: '🇵🇹' },
        { code: 'ru', name: 'Russian', flag: '🇷🇺' },
        { code: 'zh', name: 'Chinese', flag: '🇨🇳' },
        { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
        { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
        { code: 'hi', name: 'Hindi', flag: '🇮🇳' }
    ];

  private translations: { [lang: string]: Translations } = {
    en: {
      // Header
      'book_now': 'BOOK NOW',
      'my_booking': 'MY BOOKING',
      'select_language': 'Select Language',
      
      // Search
      'hotel_city': 'HOTEL/CITY',
      'search_by_hotel': 'Search By Hotel/City',
      'check_in': 'CHECK IN',
      'check_out': 'CHECK OUT',
      'room': 'ROOM',
      'rooms': 'Rooms',
      'adults': 'Adults',
      'children': 'Children',
      'search': 'Search',
      'search_results': 'SEARCH RESULTS',
      'hotel_details': 'Hotel Details',
      'my_cart': 'My Cart',
      
      // Package/Room
      'view_details': 'View Details',
      'select_room': 'Select Room',
      'per_night': 'per night',
      'amenities': 'Amenities',
      'key_amenities': 'Key Amenities',
      'room_type': 'Room Type',
      'rate_plan': 'Rate Plan',
      'price': 'Price',
      'total': 'Total',
      'book': 'Book',
      'add_to_cart': 'ADD TO CART',
      'cart_full': 'CART FULL',
      'remove': 'Remove',
      'overview': 'Overview',
      'address': 'Address',
      'click_to_view': 'Click to view details',
      'view_more': 'View More',
      'view_less': 'View Less',
      'our_lowest_price': 'Our lowest price',
      'good_to_know': 'Good to know',
      'checkin_checkout': 'Checkin & checkout',
      'room_details': 'Room Details',
      'max_person': 'Max Person',
      'max_children': 'Max Children',
      'base_occupancy': 'Base Occupancy',
      'meal_plan': 'Meal Plan',
      'inclusions': 'Inclusions',
      'view_more_rates': 'View More Rates',
      'view_less_rates': 'View Less Rates',
      'deal_name': 'Deal Name',
      'description': 'Description',
      'value': 'Value',
      
      // Cart
      'cart_summary': 'Cart Summary',
      'check_in_date': 'Check-in Date',
      'check_out_date': 'Check-out Date',
      'nights': 'Nights',
      'night': 'night',
      'guests': 'Guests',
      'room_charges': 'Room Charges',
      'taxes_fees': 'plus taxes and charges',
      'tax_per_night': 'Tax (per night)',
      'grand_total': 'GRAND TOTAL',
      'proceed_to_book': 'Proceed to Book',
      'reserve_now': 'RESERVE NOW',
      'original_price': 'Original Price',
      'deal_discount': 'Deal Discount',
      'promo_discount': 'Promo Discount',
      'hotel_name': 'Hotel Name',
      'no_room_selected': 'You have not selected any room for booking!',
      'more_rooms_needed': 'More Room(s) Needed',
      'select_more_rooms': 'Please select more rooms to complete your booking',
      
      // Booking
      'addons': 'Add-ons',
      'personal_details': 'PERSONAL DETAILS',
      'confirmation': 'Confirmation',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'email': 'Email Address',
      'phone': 'Phone',
      'country': 'Country',
      'special_requests': 'Special Requests',
      'continue': 'Continue',
      'back': 'Back',
      'confirm_booking': 'Confirm Booking',
      'pay_now': 'Pay Now',
      'pay_at_hotel': 'Pay at Hotel',
      'payment': 'Payment',
      'hotels_resorts': 'Hotels & Resorts',
      'lane_address': 'Lane Address',
      'city': 'City',
      'state': 'State',
      'promo_code': 'Promo Code',
      'apply_code': 'Apply Code',
      'validating': 'Validating...',
      'applied': 'Applied',
      'clear': 'Clear',
      'add_notes': 'Add any notes here',
      'enter_promo': 'Enter Corporate / Promotional Code',
      
      // Confirmation
      'booking_confirmed': 'BOOKING CONFIRMED',
      'booking_id': 'BOOKING ID',
      'thank_you': 'Thank you for your booking!',
      'confirmation_email': 'A confirmation email has been sent to your email address.',
      'package_summary': 'PACKAGE SUMMARY',
      'tariffs': 'TARIFFS',
      'no_addons': 'No addons selected',
      'others': 'Others',
      
      // Deals
      'deals': 'DEALS',
      'special_offers': 'Special Offers',
      'valid_until': 'Valid Until',
      'view_deal': 'View Deal',
      'offer_available': 'Offer available for stays between',
      'bookings_made_between': 'For bookings made between',
      
      // Footer
      'contact_us': 'Contact Us',
      'about_us': 'About Us',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'all_rights_reserved': 'All Rights Reserved',
      
      // Common
      'loading': 'Loading...',
      'no_results': 'No results found',
      'error': 'An error occurred',
      'try_again': 'Try Again',
      'close': 'Close',
      'save': 'Save',
      'cancel': 'Cancel',
      'yes': 'Yes',
      'no': 'No'
    },
    
    es: {
      // Header
      'book_now': 'RESERVAR AHORA',
      'my_booking': 'MI RESERVA',
      'select_language': 'Seleccionar Idioma',
      
      // Search
      'hotel_city': 'HOTEL/CIUDAD',
      'search_by_hotel': 'Buscar por Hotel/Ciudad',
      'check_in': 'ENTRADA',
      'check_out': 'SALIDA',
      'room': 'HABITACIÓN',
      'rooms': 'Habitaciones',
      'adults': 'Adultos',
      'children': 'Niños',
      'search': 'Buscar',
      'search_results': 'RESULTADOS DE BÚSQUEDA',
      'hotel_details': 'Detalles del Hotel',
      'my_cart': 'Mi Carrito',
      
      // Package/Room
      'view_details': 'Ver Detalles',
      'select_room': 'Seleccionar Habitación',
      'per_night': 'por noche',
      'amenities': 'Comodidades',
      'key_amenities': 'Comodidades Principales',
      'room_type': 'Tipo de Habitación',
      'rate_plan': 'Plan de Tarifa',
      'price': 'Precio',
      'total': 'Total',
      'book': 'Reservar',
      'add_to_cart': 'AGREGAR AL CARRITO',
      'cart_full': 'CARRITO LLENO',
      'remove': 'Eliminar',
      'overview': 'Descripción General',
      'address': 'Dirección',
      'click_to_view': 'Clic para ver detalles',
      'view_more': 'Ver Más',
      'view_less': 'Ver Menos',
      'our_lowest_price': 'Nuestro precio más bajo',
      'good_to_know': 'Bueno saber',
      'checkin_checkout': 'Entrada y Salida',
      'room_details': 'Detalles de Habitación',
      'max_person': 'Máx. Personas',
      'max_children': 'Máx. Niños',
      'base_occupancy': 'Ocupación Base',
      'meal_plan': 'Plan de Comidas',
      'inclusions': 'Incluye',
      'view_more_rates': 'Ver Más Tarifas',
      'view_less_rates': 'Ver Menos Tarifas',
      'deal_name': 'Nombre de Oferta',
      'description': 'Descripción',
      'value': 'Valor',
      
      // Cart
      'cart_summary': 'Resumen del Carrito',
      'check_in_date': 'Fecha de Entrada',
      'check_out_date': 'Fecha de Salida',
      'nights': 'Noches',
      'night': 'noche',
      'guests': 'Huéspedes',
      'room_charges': 'Cargos de Habitación',
      'taxes_fees': 'más impuestos y cargos',
      'tax_per_night': 'Impuesto (por noche)',
      'grand_total': 'TOTAL GENERAL',
      'proceed_to_book': 'Proceder a Reservar',
      'reserve_now': 'RESERVAR AHORA',
      'original_price': 'Precio Original',
      'deal_discount': 'Descuento de Oferta',
      'promo_discount': 'Descuento Promocional',
      'hotel_name': 'Nombre del Hotel',
      'no_room_selected': '¡No has seleccionado ninguna habitación!',
      'more_rooms_needed': 'Más Habitaciones Necesarias',
      'select_more_rooms': 'Por favor seleccione más habitaciones para completar su reserva',
      
      // Booking
      'addons': 'Extras',
      'personal_details': 'DATOS PERSONALES',
      'confirmation': 'Confirmación',
      'first_name': 'Nombre',
      'last_name': 'Apellido',
      'email': 'Correo Electrónico',
      'phone': 'Teléfono',
      'country': 'País',
      'special_requests': 'Solicitudes Especiales',
      'continue': 'Continuar',
      'back': 'Atrás',
      'confirm_booking': 'Confirmar Reserva',
      'pay_now': 'Pagar Ahora',
      'pay_at_hotel': 'Pagar en el Hotel',
      'payment': 'Pago',
      'hotels_resorts': 'Hoteles y Resorts',
      'lane_address': 'Dirección',
      'city': 'Ciudad',
      'state': 'Estado',
      'promo_code': 'Código Promocional',
      'apply_code': 'Aplicar Código',
      'validating': 'Validando...',
      'applied': 'Aplicado',
      'clear': 'Limpiar',
      'add_notes': 'Añadir notas aquí',
      'enter_promo': 'Ingrese Código Corporativo / Promocional',
      
      // Confirmation
      'booking_confirmed': 'RESERVA CONFIRMADA',
      'booking_id': 'ID DE RESERVA',
      'thank_you': '¡Gracias por su reserva!',
      'confirmation_email': 'Se ha enviado un correo de confirmación a su dirección de correo electrónico.',
      'package_summary': 'RESUMEN DEL PAQUETE',
      'tariffs': 'TARIFAS',
      'no_addons': 'Sin extras seleccionados',
      'others': 'Otros',
      
      // Deals
      'deals': 'OFERTAS',
      'special_offers': 'Ofertas Especiales',
      'valid_until': 'Válido Hasta',
      'view_deal': 'Ver Oferta',
      'offer_available': 'Oferta disponible para estancias entre',
      'bookings_made_between': 'Para reservas realizadas entre',
      
      // Footer
      'contact_us': 'Contáctenos',
      'about_us': 'Sobre Nosotros',
      'terms_conditions': 'Términos y Condiciones',
      'privacy_policy': 'Política de Privacidad',
      'all_rights_reserved': 'Todos los Derechos Reservados',
      
      // Common
      'loading': 'Cargando...',
      'no_results': 'No se encontraron resultados',
      'error': 'Ocurrió un error',
      'try_again': 'Intentar de Nuevo',
      'close': 'Cerrar',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'yes': 'Sí',
      'no': 'No'
    },
    
    fr: {
      // Header
      'book_now': 'RÉSERVER',
      'my_booking': 'MA RÉSERVATION',
      'select_language': 'Sélectionner la Langue',
      
      // Search
      'hotel_city': 'HÔTEL/VILLE',
      'search_by_hotel': 'Rechercher par Hôtel/Ville',
      'check_in': 'ARRIVÉE',
      'check_out': 'DÉPART',
      'room': 'CHAMBRE',
      'rooms': 'Chambres',
      'adults': 'Adultes',
      'children': 'Enfants',
      'search': 'Rechercher',
      'search_results': 'RÉSULTATS DE RECHERCHE',
      'hotel_details': 'Détails de l\'Hôtel',
      'my_cart': 'Mon Panier',
      
      // Package/Room
      'view_details': 'Voir les Détails',
      'select_room': 'Sélectionner la Chambre',
      'per_night': 'par nuit',
      'amenities': 'Équipements',
      'key_amenities': 'Équipements Principaux',
      'room_type': 'Type de Chambre',
      'rate_plan': 'Plan Tarifaire',
      'price': 'Prix',
      'total': 'Total',
      'book': 'Réserver',
      'add_to_cart': 'AJOUTER AU PANIER',
      'cart_full': 'PANIER PLEIN',
      'remove': 'Supprimer',
      'overview': 'Aperçu',
      'address': 'Adresse',
      'click_to_view': 'Cliquez pour voir les détails',
      'view_more': 'Voir Plus',
      'view_less': 'Voir Moins',
      'our_lowest_price': 'Notre prix le plus bas',
      'good_to_know': 'Bon à savoir',
      'checkin_checkout': 'Arrivée et Départ',
      'room_details': 'Détails de la Chambre',
      'max_person': 'Pers. Max',
      'max_children': 'Enfants Max',
      'base_occupancy': 'Occupation de Base',
      'meal_plan': 'Plan Repas',
      'inclusions': 'Inclus',
      'view_more_rates': 'Voir Plus de Tarifs',
      'view_less_rates': 'Voir Moins de Tarifs',
      'deal_name': 'Nom de l\'Offre',
      'description': 'Description',
      'value': 'Valeur',
      
      // Cart
      'cart_summary': 'Résumé du Panier',
      'check_in_date': 'Date d\'Arrivée',
      'check_out_date': 'Date de Départ',
      'nights': 'Nuits',
      'night': 'nuit',
      'guests': 'Invités',
      'room_charges': 'Frais de Chambre',
      'taxes_fees': 'taxes et frais inclus',
      'tax_per_night': 'Taxe (par nuit)',
      'grand_total': 'TOTAL GÉNÉRAL',
      'proceed_to_book': 'Procéder à la Réservation',
      'reserve_now': 'RÉSERVER MAINTENANT',
      'original_price': 'Prix Original',
      'deal_discount': 'Remise Offre',
      'promo_discount': 'Remise Promo',
      'hotel_name': 'Nom de l\'Hôtel',
      'no_room_selected': 'Vous n\'avez pas sélectionné de chambre!',
      'more_rooms_needed': 'Plus de Chambres Nécessaires',
      'select_more_rooms': 'Veuillez sélectionner plus de chambres pour compléter votre réservation',
      
      // Booking
      'addons': 'Suppléments',
      'personal_details': 'COORDONNÉES PERSONNELLES',
      'confirmation': 'Confirmation',
      'first_name': 'Prénom',
      'last_name': 'Nom',
      'email': 'E-mail',
      'phone': 'Téléphone',
      'country': 'Pays',
      'special_requests': 'Demandes Spéciales',
      'continue': 'Continuer',
      'back': 'Retour',
      'confirm_booking': 'Confirmer la Réservation',
      'pay_now': 'Payer Maintenant',
      'pay_at_hotel': 'Payer à l\'Hôtel',
      'payment': 'Paiement',
      'hotels_resorts': 'Hôtels et Resorts',
      'lane_address': 'Adresse',
      'city': 'Ville',
      'state': 'État/Région',
      'promo_code': 'Code Promo',
      'apply_code': 'Appliquer le Code',
      'validating': 'Validation...',
      'applied': 'Appliqué',
      'clear': 'Effacer',
      'add_notes': 'Ajouter des notes ici',
      'enter_promo': 'Entrez Code Entreprise / Promotionnel',
      
      // Confirmation
      'booking_confirmed': 'RÉSERVATION CONFIRMÉE',
      'booking_id': 'ID DE RÉSERVATION',
      'thank_you': 'Merci pour votre réservation!',
      'confirmation_email': 'Un e-mail de confirmation a été envoyé à votre adresse e-mail.',
      'package_summary': 'RÉSUMÉ DU FORFAIT',
      'tariffs': 'TARIFS',
      'no_addons': 'Aucun supplément sélectionné',
      'others': 'Autres',
      
      // Deals
      'deals': 'OFFRES',
      'special_offers': 'Offres Spéciales',
      'valid_until': 'Valable Jusqu\'au',
      'view_deal': 'Voir l\'Offre',
      'offer_available': 'Offre disponible pour les séjours entre',
      'bookings_made_between': 'Pour les réservations effectuées entre',
      
      // Footer
      'contact_us': 'Contactez-nous',
      'about_us': 'À Propos',
      'terms_conditions': 'Conditions Générales',
      'privacy_policy': 'Politique de Confidentialité',
      'all_rights_reserved': 'Tous Droits Réservés',
      
      // Common
      'loading': 'Chargement...',
      'no_results': 'Aucun résultat trouvé',
      'error': 'Une erreur s\'est produite',
      'try_again': 'Réessayer',
      'close': 'Fermer',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'yes': 'Oui',
      'no': 'Non'
    },
    
    de: {
      // Header
      'book_now': 'JETZT BUCHEN',
      'my_booking': 'MEINE BUCHUNG',
      'select_language': 'Sprache Auswählen',
      
      // Search
      'hotel_city': 'HOTEL/STADT',
      'search_by_hotel': 'Nach Hotel/Stadt suchen',
      'check_in': 'ANREISE',
      'check_out': 'ABREISE',
      'room': 'ZIMMER',
      'rooms': 'Zimmer',
      'adults': 'Erwachsene',
      'children': 'Kinder',
      'search': 'Suchen',
      'search_results': 'SUCHERGEBNISSE',
      'hotel_details': 'Hoteldetails',
      'my_cart': 'Mein Warenkorb',
      
      // Package/Room
      'view_details': 'Details Anzeigen',
      'select_room': 'Zimmer Auswählen',
      'per_night': 'pro Nacht',
      'amenities': 'Ausstattung',
      'key_amenities': 'Hauptausstattung',
      'room_type': 'Zimmertyp',
      'rate_plan': 'Tarifplan',
      'price': 'Preis',
      'total': 'Gesamt',
      'book': 'Buchen',
      'add_to_cart': 'IN DEN WARENKORB',
      'cart_full': 'WARENKORB VOLL',
      'remove': 'Entfernen',
      'overview': 'Übersicht',
      'address': 'Adresse',
      'click_to_view': 'Klicken Sie für Details',
      'view_more': 'Mehr Anzeigen',
      'view_less': 'Weniger Anzeigen',
      'our_lowest_price': 'Unser niedrigster Preis',
      'good_to_know': 'Gut zu wissen',
      'checkin_checkout': 'An- und Abreise',
      'room_details': 'Zimmerdetails',
      'max_person': 'Max. Personen',
      'max_children': 'Max. Kinder',
      'base_occupancy': 'Grundbelegung',
      'meal_plan': 'Verpflegung',
      'inclusions': 'Inklusive',
      'view_more_rates': 'Mehr Tarife Anzeigen',
      'view_less_rates': 'Weniger Tarife Anzeigen',
      'deal_name': 'Angebotsname',
      'description': 'Beschreibung',
      'value': 'Wert',
      
      // Cart
      'cart_summary': 'Warenkorb Übersicht',
      'check_in_date': 'Anreisedatum',
      'check_out_date': 'Abreisedatum',
      'nights': 'Nächte',
      'night': 'Nacht',
      'guests': 'Gäste',
      'room_charges': 'Zimmergebühren',
      'taxes_fees': 'inkl. Steuern & Gebühren',
      'tax_per_night': 'Steuer (pro Nacht)',
      'grand_total': 'GESAMTSUMME',
      'proceed_to_book': 'Zur Buchung',
      'reserve_now': 'JETZT RESERVIEREN',
      'original_price': 'Originalpreis',
      'deal_discount': 'Angebotsrabatt',
      'promo_discount': 'Promo-Rabatt',
      'hotel_name': 'Hotelname',
      'no_room_selected': 'Sie haben kein Zimmer ausgewählt!',
      'more_rooms_needed': 'Mehr Zimmer Benötigt',
      'select_more_rooms': 'Bitte wählen Sie mehr Zimmer aus, um Ihre Buchung abzuschließen',
      
      // Booking
      'addons': 'Extras',
      'personal_details': 'PERSÖNLICHE DATEN',
      'confirmation': 'Bestätigung',
      'first_name': 'Vorname',
      'last_name': 'Nachname',
      'email': 'E-Mail',
      'phone': 'Telefon',
      'country': 'Land',
      'special_requests': 'Besondere Wünsche',
      'continue': 'Weiter',
      'back': 'Zurück',
      'confirm_booking': 'Buchung Bestätigen',
      'pay_now': 'Jetzt Bezahlen',
      'pay_at_hotel': 'Im Hotel Bezahlen',
      'payment': 'Zahlung',
      'hotels_resorts': 'Hotels & Resorts',
      'lane_address': 'Straßenadresse',
      'city': 'Stadt',
      'state': 'Bundesland',
      'promo_code': 'Promo-Code',
      'apply_code': 'Code Anwenden',
      'validating': 'Validierung...',
      'applied': 'Angewendet',
      'clear': 'Löschen',
      'add_notes': 'Notizen hier hinzufügen',
      'enter_promo': 'Firmen-/Aktionscode eingeben',
      
      // Confirmation
      'booking_confirmed': 'BUCHUNG BESTÄTIGT',
      'booking_id': 'BUCHUNGS-ID',
      'thank_you': 'Vielen Dank für Ihre Buchung!',
      'confirmation_email': 'Eine Bestätigungs-E-Mail wurde an Ihre E-Mail-Adresse gesendet.',
      'package_summary': 'PAKETÜBERSICHT',
      'tariffs': 'TARIFE',
      'no_addons': 'Keine Extras ausgewählt',
      'others': 'Sonstiges',
      
      // Deals
      'deals': 'ANGEBOTE',
      'special_offers': 'Sonderangebote',
      'valid_until': 'Gültig Bis',
      'view_deal': 'Angebot Ansehen',
      'offer_available': 'Angebot verfügbar für Aufenthalte zwischen',
      'bookings_made_between': 'Für Buchungen zwischen',
      
      // Footer
      'contact_us': 'Kontakt',
      'about_us': 'Über Uns',
      'terms_conditions': 'AGB',
      'privacy_policy': 'Datenschutz',
      'all_rights_reserved': 'Alle Rechte Vorbehalten',
      
      // Common
      'loading': 'Laden...',
      'no_results': 'Keine Ergebnisse gefunden',
      'error': 'Ein Fehler ist aufgetreten',
      'try_again': 'Erneut Versuchen',
      'close': 'Schließen',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'yes': 'Ja',
      'no': 'Nein'
    },
    
    hi: {
      // Header
      'book_now': 'अभी बुक करें',
      'my_booking': 'मेरी बुकिंग',
      'select_language': 'भाषा चुनें',
      
      // Search
      'hotel_city': 'होटल/शहर',
      'search_by_hotel': 'होटल/शहर द्वारा खोजें',
      'check_in': 'चेक इन',
      'check_out': 'चेक आउट',
      'room': 'कमरा',
      'rooms': 'कमरे',
      'adults': 'वयस्क',
      'children': 'बच्चे',
      'search': 'खोजें',
      'search_results': 'खोज परिणाम',
      'hotel_details': 'होटल विवरण',
      'my_cart': 'मेरी कार्ट',
      
      // Package/Room
      'view_details': 'विवरण देखें',
      'select_room': 'कमरा चुनें',
      'per_night': 'प्रति रात',
      'amenities': 'सुविधाएं',
      'key_amenities': 'मुख्य सुविधाएं',
      'room_type': 'कमरे का प्रकार',
      'rate_plan': 'दर योजना',
      'price': 'कीमत',
      'total': 'कुल',
      'book': 'बुक करें',
      'add_to_cart': 'कार्ट में जोड़ें',
      'cart_full': 'कार्ट भरी हुई है',
      'remove': 'हटाएं',
      'overview': 'अवलोकन',
      'address': 'पता',
      'click_to_view': 'विवरण देखने के लिए क्लिक करें',
      'view_more': 'और देखें',
      'view_less': 'कम देखें',
      'our_lowest_price': 'हमारी सबसे कम कीमत',
      'good_to_know': 'जानने योग्य',
      'checkin_checkout': 'चेक-इन और चेक-आउट',
      'room_details': 'कमरे का विवरण',
      'max_person': 'अधिकतम व्यक्ति',
      'max_children': 'अधिकतम बच्चे',
      'base_occupancy': 'आधार अधिभोग',
      'meal_plan': 'भोजन योजना',
      'inclusions': 'शामिल',
      'view_more_rates': 'और दरें देखें',
      'view_less_rates': 'कम दरें देखें',
      'deal_name': 'डील का नाम',
      'description': 'विवरण',
      'value': 'मूल्य',
      
      // Cart
      'cart_summary': 'कार्ट सारांश',
      'check_in_date': 'चेक-इन तिथि',
      'check_out_date': 'चेक-आउट तिथि',
      'nights': 'रातें',
      'night': 'रात',
      'guests': 'मेहमान',
      'room_charges': 'कमरे का शुल्क',
      'taxes_fees': 'करों और शुल्कों के साथ',
      'tax_per_night': 'कर (प्रति रात)',
      'grand_total': 'कुल योग',
      'proceed_to_book': 'बुकिंग के लिए आगे बढ़ें',
      'reserve_now': 'अभी आरक्षित करें',
      'original_price': 'मूल कीमत',
      'deal_discount': 'डील छूट',
      'promo_discount': 'प्रोमो छूट',
      'hotel_name': 'होटल का नाम',
      'no_room_selected': 'आपने बुकिंग के लिए कोई कमरा नहीं चुना है!',
      'more_rooms_needed': 'और कमरों की आवश्यकता',
      'select_more_rooms': 'कृपया अपनी बुकिंग पूरी करने के लिए और कमरे चुनें',
      
      // Booking
      'addons': 'अतिरिक्त',
      'personal_details': 'व्यक्तिगत विवरण',
      'confirmation': 'पुष्टि',
      'first_name': 'पहला नाम',
      'last_name': 'अंतिम नाम',
      'email': 'ईमेल',
      'phone': 'फ़ोन',
      'country': 'देश',
      'special_requests': 'विशेष अनुरोध',
      'continue': 'जारी रखें',
      'back': 'वापस',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'pay_now': 'अभी भुगतान करें',
      'pay_at_hotel': 'होटल में भुगतान करें',
      'payment': 'भुगतान',
      'hotels_resorts': 'होटल और रिसॉर्ट',
      'lane_address': 'गली का पता',
      'city': 'शहर',
      'state': 'राज्य',
      'promo_code': 'प्रोमो कोड',
      'apply_code': 'कोड लागू करें',
      'validating': 'सत्यापन हो रहा है...',
      'applied': 'लागू',
      'clear': 'हटाएं',
      'add_notes': 'यहां कोई नोट्स जोड़ें',
      'enter_promo': 'कॉर्पोरेट / प्रचार कोड दर्ज करें',
      
      // Confirmation
      'booking_confirmed': 'बुकिंग की पुष्टि',
      'booking_id': 'बुकिंग आईडी',
      'thank_you': 'आपकी बुकिंग के लिए धन्यवाद!',
      'confirmation_email': 'आपके ईमेल पते पर एक पुष्टिकरण ईमेल भेजा गया है।',
      'package_summary': 'पैकेज सारांश',
      'tariffs': 'दरें',
      'no_addons': 'कोई ऐडऑन नहीं चुना गया',
      'others': 'अन्य',
      
      // Deals
      'deals': 'ऑफर',
      'special_offers': 'विशेष ऑफर',
      'valid_until': 'वैध तक',
      'view_deal': 'ऑफर देखें',
      'offer_available': 'ठहरने के लिए ऑफर उपलब्ध',
      'bookings_made_between': 'बुकिंग की अवधि',
      
      // Footer
      'contact_us': 'संपर्क करें',
      'about_us': 'हमारे बारे में',
      'terms_conditions': 'नियम और शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'all_rights_reserved': 'सर्वाधिकार सुरक्षित',
      
      // Common
      'loading': 'लोड हो रहा है...',
      'no_results': 'कोई परिणाम नहीं मिला',
      'error': 'एक त्रुटि हुई',
      'try_again': 'पुनः प्रयास करें',
      'close': 'बंद करें',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'yes': 'हाँ',
      'no': 'नहीं'
    },
    
    zh: {
      // Header
      'book_now': '立即预订',
      'my_booking': '我的预订',
      'select_language': '选择语言',
      
      // Search
      'hotel_city': '酒店/城市',
      'search_by_hotel': '按酒店/城市搜索',
      'check_in': '入住',
      'check_out': '退房',
      'room': '房间',
      'rooms': '房间',
      'adults': '成人',
      'children': '儿童',
      'search': '搜索',
      'search_results': '搜索结果',
      'hotel_details': '酒店详情',
      'my_cart': '我的购物车',
      
      // Package/Room
      'view_details': '查看详情',
      'select_room': '选择房间',
      'per_night': '每晚',
      'amenities': '设施',
      'key_amenities': '主要设施',
      'room_type': '房间类型',
      'rate_plan': '房价计划',
      'price': '价格',
      'total': '总计',
      'book': '预订',
      'add_to_cart': '加入购物车',
      'cart_full': '购物车已满',
      'remove': '移除',
      'overview': '概述',
      'address': '地址',
      'click_to_view': '点击查看详情',
      'view_more': '查看更多',
      'view_less': '收起',
      'our_lowest_price': '最低价格',
      'good_to_know': '须知',
      'checkin_checkout': '入住和退房',
      'room_details': '房间详情',
      'max_person': '最多入住',
      'max_children': '最多儿童',
      'base_occupancy': '基本入住人数',
      'meal_plan': '餐饮计划',
      'inclusions': '包含',
      'view_more_rates': '查看更多价格',
      'view_less_rates': '收起价格',
      'deal_name': '优惠名称',
      'description': '描述',
      'value': '价值',
      
      // Cart
      'cart_summary': '购物车摘要',
      'check_in_date': '入住日期',
      'check_out_date': '退房日期',
      'nights': '晚',
      'night': '晚',
      'guests': '客人',
      'room_charges': '房费',
      'taxes_fees': '含税费',
      'tax_per_night': '税费（每晚）',
      'grand_total': '总计',
      'proceed_to_book': '继续预订',
      'reserve_now': '立即预订',
      'original_price': '原价',
      'deal_discount': '优惠折扣',
      'promo_discount': '促销折扣',
      'hotel_name': '酒店名称',
      'no_room_selected': '您尚未选择房间！',
      'more_rooms_needed': '需要更多房间',
      'select_more_rooms': '请选择更多房间以完成预订',
      
      // Booking
      'addons': '附加服务',
      'personal_details': '个人信息',
      'confirmation': '确认',
      'first_name': '名',
      'last_name': '姓',
      'email': '电子邮件',
      'phone': '电话',
      'country': '国家',
      'special_requests': '特殊要求',
      'continue': '继续',
      'back': '返回',
      'confirm_booking': '确认预订',
      'pay_now': '立即支付',
      'pay_at_hotel': '到店付款',
      'payment': '付款',
      'hotels_resorts': '酒店和度假村',
      'lane_address': '街道地址',
      'city': '城市',
      'state': '省/州',
      'promo_code': '促销代码',
      'apply_code': '应用代码',
      'validating': '验证中...',
      'applied': '已应用',
      'clear': '清除',
      'add_notes': '在此添加备注',
      'enter_promo': '输入企业/促销代码',
      
      // Confirmation
      'booking_confirmed': '预订已确认',
      'booking_id': '预订编号',
      'thank_you': '感谢您的预订！',
      'confirmation_email': '确认邮件已发送至您的邮箱。',
      'package_summary': '套餐摘要',
      'tariffs': '价格',
      'no_addons': '未选择附加服务',
      'others': '其他',
      
      // Deals
      'deals': '优惠',
      'special_offers': '特别优惠',
      'valid_until': '有效期至',
      'view_deal': '查看优惠',
      'offer_available': '优惠适用于入住日期',
      'bookings_made_between': '预订日期范围',
      
      // Footer
      'contact_us': '联系我们',
      'about_us': '关于我们',
      'terms_conditions': '条款和条件',
      'privacy_policy': '隐私政策',
      'all_rights_reserved': '版权所有',
      
      // Common
      'loading': '加载中...',
      'no_results': '未找到结果',
      'error': '发生错误',
      'try_again': '重试',
      'close': '关闭',
      'save': '保存',
      'cancel': '取消',
      'yes': '是',
      'no': '否'
    },
    
    ja: {
      // Header
      'book_now': '今すぐ予約',
      'my_booking': '予約確認',
      'select_language': '言語を選択',
      
      // Search
      'hotel_city': 'ホテル/都市',
      'search_by_hotel': 'ホテル/都市で検索',
      'check_in': 'チェックイン',
      'check_out': 'チェックアウト',
      'room': '部屋',
      'rooms': '部屋',
      'adults': '大人',
      'children': '子供',
      'search': '検索',
      'search_results': '検索結果',
      'hotel_details': 'ホテル詳細',
      'my_cart': 'カート',
      
      // Package/Room
      'view_details': '詳細を見る',
      'select_room': '部屋を選択',
      'per_night': '1泊',
      'amenities': 'アメニティ',
      'key_amenities': '主要アメニティ',
      'room_type': '部屋タイプ',
      'rate_plan': '料金プラン',
      'price': '価格',
      'total': '合計',
      'book': '予約',
      'add_to_cart': 'カートに追加',
      'cart_full': 'カートがいっぱいです',
      'remove': '削除',
      'overview': '概要',
      'address': '住所',
      'click_to_view': '詳細を見るにはクリック',
      'view_more': 'もっと見る',
      'view_less': '閉じる',
      'our_lowest_price': '最安値',
      'good_to_know': '知っておきたいこと',
      'checkin_checkout': 'チェックイン・チェックアウト',
      'room_details': '部屋の詳細',
      'max_person': '最大人数',
      'max_children': '最大子供数',
      'base_occupancy': '基本定員',
      'meal_plan': '食事プラン',
      'inclusions': '含まれるもの',
      'view_more_rates': '他の料金を見る',
      'view_less_rates': '料金を閉じる',
      'deal_name': 'セール名',
      'description': '説明',
      'value': '価値',
      
      // Cart
      'cart_summary': 'カート概要',
      'check_in_date': 'チェックイン日',
      'check_out_date': 'チェックアウト日',
      'nights': '泊',
      'night': '泊',
      'guests': 'ゲスト',
      'room_charges': '客室料金',
      'taxes_fees': '税金・手数料込み',
      'tax_per_night': '税金（1泊あたり）',
      'grand_total': '合計金額',
      'proceed_to_book': '予約に進む',
      'reserve_now': '今すぐ予約',
      'original_price': '元の価格',
      'deal_discount': 'セール割引',
      'promo_discount': 'プロモ割引',
      'hotel_name': 'ホテル名',
      'no_room_selected': '部屋が選択されていません！',
      'more_rooms_needed': '追加の部屋が必要',
      'select_more_rooms': '予約を完了するには、さらに部屋を選択してください',
      
      // Booking
      'addons': 'オプション',
      'personal_details': '個人情報',
      'confirmation': '確認',
      'first_name': '名',
      'last_name': '姓',
      'email': 'メール',
      'phone': '電話',
      'country': '国',
      'special_requests': '特別リクエスト',
      'continue': '続ける',
      'back': '戻る',
      'confirm_booking': '予約を確定',
      'pay_now': '今すぐ支払う',
      'pay_at_hotel': 'ホテルで支払う',
      'payment': 'お支払い',
      'hotels_resorts': 'ホテル＆リゾート',
      'lane_address': '番地',
      'city': '市区町村',
      'state': '都道府県',
      'promo_code': 'プロモコード',
      'apply_code': 'コードを適用',
      'validating': '確認中...',
      'applied': '適用済み',
      'clear': 'クリア',
      'add_notes': 'メモを追加',
      'enter_promo': '企業/プロモコードを入力',
      
      // Confirmation
      'booking_confirmed': '予約完了',
      'booking_id': '予約番号',
      'thank_you': 'ご予約ありがとうございます！',
      'confirmation_email': '確認メールをお送りしました。',
      'package_summary': 'パッケージ概要',
      'tariffs': '料金',
      'no_addons': 'オプションなし',
      'others': 'その他',
      
      // Deals
      'deals': 'セール',
      'special_offers': '特別オファー',
      'valid_until': '有効期限',
      'view_deal': 'セールを見る',
      'offer_available': '宿泊期間の対象オファー',
      'bookings_made_between': '予約期間',
      
      // Footer
      'contact_us': 'お問い合わせ',
      'about_us': '私たちについて',
      'terms_conditions': '利用規約',
      'privacy_policy': 'プライバシーポリシー',
      'all_rights_reserved': '全著作権所有',
      
      // Common
      'loading': '読み込み中...',
      'no_results': '結果が見つかりません',
      'error': 'エラーが発生しました',
      'try_again': '再試行',
      'close': '閉じる',
      'save': '保存',
      'cancel': 'キャンセル',
      'yes': 'はい',
      'no': 'いいえ'
    },
    
    ar: {
      // Header
      'book_now': 'احجز الآن',
      'my_booking': 'حجزي',
      'select_language': 'اختر اللغة',
      
      // Search
      'hotel_city': 'الفندق/المدينة',
      'search_by_hotel': 'البحث حسب الفندق/المدينة',
      'check_in': 'تسجيل الدخول',
      'check_out': 'تسجيل الخروج',
      'room': 'غرفة',
      'rooms': 'غرف',
      'adults': 'بالغين',
      'children': 'أطفال',
      'search': 'بحث',
      'search_results': 'نتائج البحث',
      'hotel_details': 'تفاصيل الفندق',
      'my_cart': 'سلتي',
      
      // Package/Room
      'view_details': 'عرض التفاصيل',
      'select_room': 'اختر الغرفة',
      'per_night': 'لليلة',
      'amenities': 'وسائل الراحة',
      'key_amenities': 'المرافق الرئيسية',
      'room_type': 'نوع الغرفة',
      'rate_plan': 'خطة السعر',
      'price': 'السعر',
      'total': 'المجموع',
      'book': 'احجز',
      'add_to_cart': 'أضف إلى السلة',
      'cart_full': 'السلة ممتلئة',
      'remove': 'إزالة',
      'overview': 'نظرة عامة',
      'address': 'العنوان',
      'click_to_view': 'انقر لعرض التفاصيل',
      'view_more': 'عرض المزيد',
      'view_less': 'عرض أقل',
      'our_lowest_price': 'أقل سعر لدينا',
      'good_to_know': 'من الجيد معرفته',
      'checkin_checkout': 'تسجيل الدخول والخروج',
      'room_details': 'تفاصيل الغرفة',
      'max_person': 'الحد الأقصى للأشخاص',
      'max_children': 'الحد الأقصى للأطفال',
      'base_occupancy': 'الإشغال الأساسي',
      'meal_plan': 'خطة الوجبات',
      'inclusions': 'شامل',
      'view_more_rates': 'عرض المزيد من الأسعار',
      'view_less_rates': 'عرض أسعار أقل',
      'deal_name': 'اسم العرض',
      'description': 'الوصف',
      'value': 'القيمة',
      
      // Cart
      'cart_summary': 'ملخص السلة',
      'check_in_date': 'تاريخ الوصول',
      'check_out_date': 'تاريخ المغادرة',
      'nights': 'ليالي',
      'night': 'ليلة',
      'guests': 'ضيوف',
      'room_charges': 'رسوم الغرفة',
      'taxes_fees': 'شامل الضرائب والرسوم',
      'tax_per_night': 'الضريبة (لليلة)',
      'grand_total': 'المجموع الكلي',
      'proceed_to_book': 'متابعة الحجز',
      'reserve_now': 'احجز الآن',
      'original_price': 'السعر الأصلي',
      'deal_discount': 'خصم العرض',
      'promo_discount': 'خصم ترويجي',
      'hotel_name': 'اسم الفندق',
      'no_room_selected': 'لم تقم باختيار أي غرفة!',
      'more_rooms_needed': 'المزيد من الغرف مطلوب',
      'select_more_rooms': 'يرجى اختيار المزيد من الغرف لإكمال حجزك',
      
      // Booking
      'addons': 'إضافات',
      'personal_details': 'البيانات الشخصية',
      'confirmation': 'تأكيد',
      'first_name': 'الاسم الأول',
      'last_name': 'اسم العائلة',
      'email': 'البريد الإلكتروني',
      'phone': 'الهاتف',
      'country': 'البلد',
      'special_requests': 'طلبات خاصة',
      'continue': 'متابعة',
      'back': 'رجوع',
      'confirm_booking': 'تأكيد الحجز',
      'pay_now': 'ادفع الآن',
      'pay_at_hotel': 'الدفع في الفندق',
      'payment': 'الدفع',
      'hotels_resorts': 'الفنادق والمنتجعات',
      'lane_address': 'عنوان الشارع',
      'city': 'المدينة',
      'state': 'الولاية/المنطقة',
      'promo_code': 'رمز ترويجي',
      'apply_code': 'تطبيق الرمز',
      'validating': 'جاري التحقق...',
      'applied': 'تم التطبيق',
      'clear': 'مسح',
      'add_notes': 'أضف ملاحظات هنا',
      'enter_promo': 'أدخل رمز الشركة / الترويجي',
      
      // Confirmation
      'booking_confirmed': 'تم تأكيد الحجز',
      'booking_id': 'رقم الحجز',
      'thank_you': 'شكراً لحجزك!',
      'confirmation_email': 'تم إرسال بريد التأكيد إلى عنوان بريدك الإلكتروني.',
      'package_summary': 'ملخص الباقة',
      'tariffs': 'التعريفات',
      'no_addons': 'لم يتم اختيار إضافات',
      'others': 'أخرى',
      
      // Deals
      'deals': 'عروض',
      'special_offers': 'عروض خاصة',
      'valid_until': 'صالح حتى',
      'view_deal': 'عرض العرض',
      'offer_available': 'العرض متاح للإقامة بين',
      'bookings_made_between': 'للحجوزات التي تمت بين',
      
      // Footer
      'contact_us': 'اتصل بنا',
      'about_us': 'من نحن',
      'terms_conditions': 'الشروط والأحكام',
      'privacy_policy': 'سياسة الخصوصية',
      'all_rights_reserved': 'جميع الحقوق محفوظة',
      
      // Common
      'loading': 'جاري التحميل...',
      'no_results': 'لم يتم العثور على نتائج',
      'error': 'حدث خطأ',
      'try_again': 'حاول مرة أخرى',
      'close': 'إغلاق',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'yes': 'نعم',
      'no': 'لا'
    },
    
    it: {
      // Header
      'book_now': 'PRENOTA ORA',
      'my_booking': 'LE MIE PRENOTAZIONI',
      'select_language': 'Seleziona Lingua',
      
      // Search
      'hotel_city': 'HOTEL/CITTÀ',
      'search_by_hotel': 'Cerca per Hotel/Città',
      'check_in': 'CHECK-IN',
      'check_out': 'CHECK-OUT',
      'room': 'CAMERA',
      'rooms': 'Camere',
      'adults': 'Adulti',
      'children': 'Bambini',
      'search': 'Cerca',
      'search_results': 'RISULTATI RICERCA',
      
      // Package/Room Details
      'hotel_details': 'Dettagli Hotel',
      'my_cart': 'Il Mio Carrello',
      'view_details': 'Vedi Dettagli',
      'select_room': 'Seleziona Camera',
      'per_night': 'per notte',
      'amenities': 'Servizi',
      'key_amenities': 'Servizi Principali',
      'room_type': 'Tipo Camera',
      'rate_plan': 'Piano Tariffario',
      'price': 'Prezzo',
      'total': 'Totale',
      'book': 'Prenota',
      'add_to_cart': 'Aggiungi al Carrello',
      'remove': 'Rimuovi',
      'overview': 'Panoramica',
      'address': 'Indirizzo',
      'click_to_view': 'Clicca per visualizzare',
      'view_more': 'Vedi di più',
      'view_less': 'Vedi di meno',
      'our_lowest_price': 'Il nostro prezzo più basso',
      'good_to_know': 'Da sapere',
      'checkin_checkout': 'Check-in / Check-out',
      'room_details': 'Dettagli Camera',
      'max_person': 'Max Persone',
      'max_children': 'Max Bambini',
      'base_occupancy': 'Occupazione Base',
      'meal_plan': 'Piano Pasti',
      'inclusions': 'Inclusi',
      'view_more_rates': 'Vedi più tariffe',
      'view_less_rates': 'Vedi meno tariffe',
      
      // Cart
      'cart_summary': 'Riepilogo Carrello',
      'check_in_date': 'Data Check-in',
      'check_out_date': 'Data Check-out',
      'nights': 'Notti',
      'night': 'Notte',
      'guests': 'Ospiti',
      'room_charges': 'Costo Camera',
      'taxes_fees': 'Tasse e Spese',
      'tax_per_night': 'Tassa per Notte',
      'grand_total': 'Totale Generale',
      'proceed_to_book': 'Procedi alla Prenotazione',
      'reserve_now': 'Prenota Ora',
      'hotel_name': 'Nome Hotel',
      'no_room_selected': 'Nessuna camera selezionata',
      'more_rooms_needed': 'Servono più camere',
      'select_more_rooms': 'Seleziona più camere',
      'cart_full': 'Carrello pieno',
      'original_price': 'Prezzo Originale',
      'deal_discount': 'Sconto Offerta',
      'promo_discount': 'Sconto Promozionale',
      'lane_address': 'Via',
      'city': 'Città',
      'state': 'Stato/Regione',
      'promo_code': 'Codice Promozionale',
      'apply_code': 'Applica Codice',
      'no_addons': 'Nessun extra selezionato',
      'others': 'Altri',
      
      // Booking
      'addons': 'Extra',
      'personal_details': 'Dati Personali',
      'confirmation': 'Conferma',
      'first_name': 'Nome',
      'last_name': 'Cognome',
      'email': 'Email',
      'phone': 'Telefono',
      'country': 'Paese',
      'special_requests': 'Richieste Speciali',
      'continue': 'Continua',
      'back': 'Indietro',
      'confirm_booking': 'Conferma Prenotazione',
      'payment': 'Pagamento',
      'pay_now': 'Paga Ora',
      'pay_at_hotel': 'Paga in Hotel',
      'hotels_resorts': 'Hotel e Resort',
      
      // Confirmation
      'booking_confirmed': 'Prenotazione Confermata',
      'booking_id': 'ID Prenotazione',
      'thank_you': 'Grazie per la tua prenotazione!',
      'confirmation_email': 'Una email di conferma è stata inviata al tuo indirizzo.',
      'package_summary': 'Riepilogo Pacchetto',
      'tariffs': 'Tariffe',
      'offer_available': 'Offerta Disponibile',
      
      // Deals
      'deals': 'OFFERTE',
      'special_offers': 'Offerte Speciali',
      'valid_until': 'Valido Fino',
      'view_deal': 'Vedi Offerta',
      'deal_name': 'Nome Offerta',
      'description': 'Descrizione',
      'value': 'Valore',
      'bookings_made_between': 'Prenotazioni effettuate tra',
      
      // Footer
      'contact_us': 'Contattaci',
      'about_us': 'Chi Siamo',
      'terms_conditions': 'Termini e Condizioni',
      'privacy_policy': 'Privacy Policy',
      'all_rights_reserved': 'Tutti i Diritti Riservati',
      
      // Common
      'loading': 'Caricamento...',
      'no_results': 'Nessun risultato trovato',
      'error': 'Si è verificato un errore',
      'try_again': 'Riprova',
      'close': 'Chiudi',
      'save': 'Salva',
      'cancel': 'Annulla',
      'yes': 'Sì',
      'no': 'No'
    },
    
    pt: {
      // Header
      'book_now': 'RESERVAR AGORA',
      'my_booking': 'MINHA RESERVA',
      'select_language': 'Selecionar Idioma',
      
      // Search
      'hotel_city': 'HOTEL/CIDADE',
      'search_by_hotel': 'Pesquisar por Hotel/Cidade',
      'check_in': 'CHECK-IN',
      'check_out': 'CHECK-OUT',
      'room': 'QUARTO',
      'rooms': 'Quartos',
      'adults': 'Adultos',
      'children': 'Crianças',
      'search': 'Pesquisar',
      'search_results': 'RESULTADOS DA PESQUISA',
      
      // Package/Room Details
      'hotel_details': 'Detalhes do Hotel',
      'my_cart': 'Meu Carrinho',
      'view_details': 'Ver Detalhes',
      'select_room': 'Selecionar Quarto',
      'per_night': 'por noite',
      'amenities': 'Comodidades',
      'key_amenities': 'Principais Comodidades',
      'room_type': 'Tipo de Quarto',
      'rate_plan': 'Plano de Tarifa',
      'price': 'Preço',
      'total': 'Total',
      'book': 'Reservar',
      'add_to_cart': 'Adicionar ao Carrinho',
      'remove': 'Remover',
      'overview': 'Visão Geral',
      'address': 'Endereço',
      'click_to_view': 'Clique para ver',
      'view_more': 'Ver mais',
      'view_less': 'Ver menos',
      'our_lowest_price': 'Nosso menor preço',
      'good_to_know': 'Bom saber',
      'checkin_checkout': 'Check-in / Check-out',
      'room_details': 'Detalhes do Quarto',
      'max_person': 'Máximo de Pessoas',
      'max_children': 'Máximo de Crianças',
      'base_occupancy': 'Ocupação Base',
      'meal_plan': 'Plano de Refeições',
      'inclusions': 'Inclusões',
      'view_more_rates': 'Ver mais tarifas',
      'view_less_rates': 'Ver menos tarifas',
      
      // Cart
      'cart_summary': 'Resumo do Carrinho',
      'check_in_date': 'Data de Check-in',
      'check_out_date': 'Data de Check-out',
      'nights': 'Noites',
      'night': 'Noite',
      'guests': 'Hóspedes',
      'room_charges': 'Taxas do Quarto',
      'taxes_fees': 'Impostos e Taxas',
      'tax_per_night': 'Imposto por Noite',
      'grand_total': 'Total Geral',
      'proceed_to_book': 'Prosseguir para Reserva',
      'reserve_now': 'Reservar Agora',
      'hotel_name': 'Nome do Hotel',
      'no_room_selected': 'Nenhum quarto selecionado',
      'more_rooms_needed': 'Mais quartos necessários',
      'select_more_rooms': 'Selecionar mais quartos',
      'cart_full': 'Carrinho cheio',
      'original_price': 'Preço Original',
      'deal_discount': 'Desconto da Oferta',
      'promo_discount': 'Desconto Promocional',
      'lane_address': 'Rua',
      'city': 'Cidade',
      'state': 'Estado',
      'promo_code': 'Código Promocional',
      'apply_code': 'Aplicar Código',
      'no_addons': 'Nenhum extra selecionado',
      'others': 'Outros',
      
      // Booking
      'addons': 'Extras',
      'personal_details': 'Dados Pessoais',
      'confirmation': 'Confirmação',
      'first_name': 'Nome',
      'last_name': 'Sobrenome',
      'email': 'E-mail',
      'phone': 'Telefone',
      'country': 'País',
      'special_requests': 'Pedidos Especiais',
      'continue': 'Continuar',
      'back': 'Voltar',
      'confirm_booking': 'Confirmar Reserva',
      'payment': 'Pagamento',
      'pay_now': 'Pagar Agora',
      'pay_at_hotel': 'Pagar no Hotel',
      'hotels_resorts': 'Hotéis e Resorts',
      
      // Confirmation
      'booking_confirmed': 'Reserva Confirmada',
      'booking_id': 'ID da Reserva',
      'thank_you': 'Obrigado pela sua reserva!',
      'confirmation_email': 'Um e-mail de confirmação foi enviado para o seu endereço.',
      'package_summary': 'Resumo do Pacote',
      'tariffs': 'Tarifas',
      'offer_available': 'Oferta Disponível',
      
      // Deals
      'deals': 'OFERTAS',
      'special_offers': 'Ofertas Especiais',
      'valid_until': 'Válido Até',
      'view_deal': 'Ver Oferta',
      'deal_name': 'Nome da Oferta',
      'description': 'Descrição',
      'value': 'Valor',
      'bookings_made_between': 'Reservas feitas entre',
      
      // Footer
      'contact_us': 'Contacte-nos',
      'about_us': 'Sobre Nós',
      'terms_conditions': 'Termos e Condições',
      'privacy_policy': 'Política de Privacidade',
      'all_rights_reserved': 'Todos os Direitos Reservados',
      
      // Common
      'loading': 'Carregando...',
      'no_results': 'Nenhum resultado encontrado',
      'error': 'Ocorreu um erro',
      'try_again': 'Tentar Novamente',
      'close': 'Fechar',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'yes': 'Sim',
      'no': 'Não'
    },
    
    ru: {
      // Header
      'book_now': 'ЗАБРОНИРОВАТЬ',
      'my_booking': 'МОЙ ЗАКАЗ',
      'select_language': 'Выбрать язык',
      
      // Search
      'hotel_city': 'ОТЕЛЬ/ГОРОД',
      'search_by_hotel': 'Поиск по отелю/городу',
      'check_in': 'ЗАЕЗД',
      'check_out': 'ВЫЕЗД',
      'room': 'НОМЕР',
      'rooms': 'Номера',
      'adults': 'Взрослые',
      'children': 'Дети',
      'search': 'Поиск',
      'search_results': 'РЕЗУЛЬТАТЫ ПОИСКА',
      
      // Package/Room Details
      'hotel_details': 'Информация об отеле',
      'my_cart': 'Моя корзина',
      'view_details': 'Подробнее',
      'select_room': 'Выбрать номер',
      'per_night': 'за ночь',
      'amenities': 'Удобства',
      'key_amenities': 'Основные удобства',
      'room_type': 'Тип номера',
      'rate_plan': 'Тарифный план',
      'price': 'Цена',
      'total': 'Итого',
      'book': 'Забронировать',
      'add_to_cart': 'В корзину',
      'remove': 'Удалить',
      'overview': 'Обзор',
      'address': 'Адрес',
      'click_to_view': 'Нажмите для просмотра',
      'view_more': 'Показать больше',
      'view_less': 'Показать меньше',
      'our_lowest_price': 'Наша лучшая цена',
      'good_to_know': 'Полезно знать',
      'checkin_checkout': 'Заезд / Выезд',
      'room_details': 'Информация о номере',
      'max_person': 'Макс. человек',
      'max_children': 'Макс. детей',
      'base_occupancy': 'Базовое размещение',
      'meal_plan': 'План питания',
      'inclusions': 'Включено',
      'view_more_rates': 'Больше тарифов',
      'view_less_rates': 'Меньше тарифов',
      
      // Cart
      'cart_summary': 'Итого в корзине',
      'check_in_date': 'Дата заезда',
      'check_out_date': 'Дата выезда',
      'nights': 'Ночей',
      'night': 'Ночь',
      'guests': 'Гости',
      'room_charges': 'Стоимость номера',
      'taxes_fees': 'Налоги и сборы',
      'tax_per_night': 'Налог за ночь',
      'grand_total': 'Общая сумма',
      'proceed_to_book': 'Перейти к бронированию',
      'reserve_now': 'Забронировать сейчас',
      'hotel_name': 'Название отеля',
      'no_room_selected': 'Номер не выбран',
      'more_rooms_needed': 'Нужно больше номеров',
      'select_more_rooms': 'Выбрать больше номеров',
      'cart_full': 'Корзина заполнена',
      'original_price': 'Исходная цена',
      'deal_discount': 'Скидка по акции',
      'promo_discount': 'Промо скидка',
      'lane_address': 'Улица',
      'city': 'Город',
      'state': 'Область',
      'promo_code': 'Промокод',
      'apply_code': 'Применить код',
      'no_addons': 'Дополнения не выбраны',
      'others': 'Другое',
      
      // Booking
      'addons': 'Дополнительно',
      'personal_details': 'Личные данные',
      'confirmation': 'Подтверждение',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'email': 'Эл. почта',
      'phone': 'Телефон',
      'country': 'Страна',
      'special_requests': 'Особые пожелания',
      'continue': 'Продолжить',
      'back': 'Назад',
      'confirm_booking': 'Подтвердить бронь',
      'payment': 'Оплата',
      'pay_now': 'Оплатить сейчас',
      'pay_at_hotel': 'Оплата в отеле',
      'hotels_resorts': 'Отели и курорты',
      
      // Confirmation
      'booking_confirmed': 'Бронирование подтверждено',
      'booking_id': 'Номер брони',
      'thank_you': 'Спасибо за бронирование!',
      'confirmation_email': 'Письмо с подтверждением отправлено на вашу почту.',
      'package_summary': 'Сводка пакета',
      'tariffs': 'Тарифы',
      'offer_available': 'Доступное предложение',
      
      // Deals
      'deals': 'АКЦИИ',
      'special_offers': 'Специальные предложения',
      'valid_until': 'Действует до',
      'view_deal': 'Смотреть акцию',
      'deal_name': 'Название акции',
      'description': 'Описание',
      'value': 'Стоимость',
      'bookings_made_between': 'Бронирование доступно между',
      
      // Footer
      'contact_us': 'Связаться с нами',
      'about_us': 'О нас',
      'terms_conditions': 'Условия использования',
      'privacy_policy': 'Политика конфиденциальности',
      'all_rights_reserved': 'Все права защищены',
      
      // Common
      'loading': 'Загрузка...',
      'no_results': 'Результаты не найдены',
      'error': 'Произошла ошибка',
      'try_again': 'Попробовать снова',
      'close': 'Закрыть',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'yes': 'Да',
      'no': 'Нет'
    }
  };

  constructor() {
    // Load saved language from localStorage
    const savedLang = this.getFromStorage('selectedLanguage');
    if (savedLang && this.translations[savedLang]) {
      this.currentLanguage.next(savedLang);
    }
  }

  private getFromStorage(key: string): string | null {
    if (typeof localStorage !== 'undefined') {
      return localStorage.getItem(key);
    }
    return null;
  }

  private setToStorage(key: string, value: string): void {
    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(key, value);
    }
  }

  setLanguage(langCode: string): void {
    if (this.translations[langCode]) {
      this.currentLanguage.next(langCode);
      this.setToStorage('selectedLanguage', langCode);
    }
  }

  getCurrentLanguage(): string {
    return this.currentLanguage.getValue();
  }

  getLanguages(): Language[] {
    return this.languages;
  }

  translate(key: string): string {
    const lang = this.currentLanguage.getValue();
    const translation = this.translations[lang]?.[key];
    
    // Fallback to English if translation not found
    if (!translation) {
      return this.translations['en']?.[key] || key;
    }
    
    return translation;
  }

  // Observable version for async pipe usage
  getTranslation(key: string): Observable<string> {
    return new Observable(observer => {
      this.currentLanguage$.subscribe(() => {
        observer.next(this.translate(key));
      });
    });
  }
}
